---
abstract: 'high level PDF creator'
author:
  - 'Andy Beverley <andy@andybev.com>'
build_requires:
  DateTime::Format::SQLite: '0'
  Test::MockObject: '0'
  Test::More: '0'
  Test::Warn: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CtrlO-PDF
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Image::Info: '0'
  Moo: '0'
  MooX::Types::MooseLike::Base: '0'
  PDF::Table: '0'
  PDF::TextBlock: '0.13'
resources:
  bugtracker: https://github.com/ctrlo/CtrlO-PDF/issues
  homepage: https://github.com/ctrlo/CtrlO-PDF/
  repository: https://github.com/ctrlo/CtrlO-PDF
version: '0.10'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
